# Generated by Django 4.1.2 on 2022-10-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chief_complaint',
            field=models.CharField(max_length=500),
        ),
    ]
