# Generated by Django 4.1.2 on 2022-10-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_prescription_patient_prescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions_Given',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Prescription Date')),
                ('time', models.TimeField()),
                ('prescription_given', models.CharField(choices=[('P', 'Pain Medication'), ('A', 'Anitbiotics'), ('F', 'Fluids')], default='P', max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
            options={
                'ordering': ('-date', '-time'),
            },
        ),
    ]
